version: 0.2

phases:
  pre_build:
    commands:
      # Retrieve an authentication token and authenticate your Docker client to your ECR registry
      - echo "Retrieving ECR authentication token..."
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/m5c8p2y7
  build:
    commands:
      # Build your Docker image
      - echo "Building Docker image..."
      - docker build -t hash-service .
      # Tag the Docker image
      - echo "Tagging Docker image..."
      - docker tag hash-service:latest public.ecr.aws/m5c8p2y7/hash-service:latest
  post_build:
    commands:
      # Push the Docker image to ECR
      - echo "Pushing Docker image to ECR..."
      - docker push public.ecr.aws/m5c8p2y7/hash-service:latest

artifacts:
  files:
    - '**/*'
