version: 0.2

phases:
  pre_build:
    commands:
      # Retrieve an authentication token and authenticate your Docker client to your ECR registry
      - echo "Retrieving ECR authentication token..."
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 671552989076.dkr.ecr.eu-central-1.amazonaws.com
  build:
    commands:
      # Build your Docker image
      - echo "Building Docker image..."
      - docker build -t hash-service .
      # Tag the Docker image
      - echo "Tagging Docker image..."
      - docker tag hash-service:latest 671552989076.dkr.ecr.eu-central-1.amazonaws.com/hash-service:latest
  post_build:
    commands:
      # Push the Docker image to ECR
      - echo "Pushing Docker image to ECR..."
      # - docker push 671552989076.dkr.ecr.eu-central-1.amazonaws.com/hash-service:latest

artifacts:
  files:
    - '**/*'
