version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR.......
      - echo REPOSITORY_URL var is $REPOSITORY_URL
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URL
      - IMAGE_REPOSITORY_URL=build-$(echo $CODEBUILD_BUILD_NUMBER)

  build:
    commands:
      - echo Build started on date
      - echo Installing Node.js dependencies...
      - npm install
      - echo Building the NestJS project...
      - npm run build
      - echo Docker image is building...
      - docker build -t $REPOSITORY_URL:latest .
      - docker REPOSITORY_URL $REPOSITORY_URL:latest $REPOSITORY_URL:$IMAGE_REPOSITORY_URL

  post_build:
    commands:
      - echo Build completed on date
      - echo Pushing Docker image to AWS ECR .....
      - docker push $REPOSITORY_URL:$IMAGE_REPOSITORY_URL
      - echo ECS Configuration....
      - echo Writing image definitions file...
      - CONTAINER_NAME=test-api
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URL:$IMAGE_REPOSITORY_URL > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

cache:
  paths:
    - 'node_modules/**/*'
